# Generated by Django 4.1.7 on 2023-02-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancesapp', '0003_remove_ownedpokemon_user_ownedpokemon_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='created',
        ),
        migrations.RemoveField(
            model_name='area',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='updated',
        ),
    ]
