# Generated by Django 4.1.7 on 2023-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
