# Generated by Django 4.1.7 on 2023-02-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancesapp', '0004_remove_area_created_remove_area_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_admin',
            new_name='is_manager',
        ),
    ]
