# Generated by Django 4.1.7 on 2023-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancesapp", "0005_rename_is_admin_player_is_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
