# Generated by Django 4.1.7 on 2023-04-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancesapp', '0007_remove_area_size_area_image_alter_pokemon_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedpokemon',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_pokemons', to='vacancesapp.pokemon'),
        ),
    ]
